CUDA_VISIBLE_DEVICES=0 python -m tevatron.retriever.driver.encode \
  --output_dir temp \
  --model_type adder \
  --model_name_or_path $MODEL_NAME \
  --query_prefix "Query: " \
  --bf16 \
  --normalize \
  --encode_is_query \
  --per_device_eval_batch_size 128 \
  --query_max_len 32 \
  --passage_max_len 180 \
  --dataset_name Tevatron/msmarco-passage \
  --dataset_name json \
  --dataset_split train \
  --dataset_path https://huggingface.co/datasets/Tevatron/msmarco-passage/resolve/main/dev.jsonl.gz \
  --encode_output_path $EMBEDDING_OUTPUT_DIR/query-dev.pkl \
  --attn_implementation sdpa \
