CUDA_VISIBLE_DEVICES=0 python -m tevatron.retriever.driver.encode \
  --output_dir temp \
  --model_type adder \
  --model_name_or_path $1 \
  --query_prefix "Query: " \
  --bf16 \
  --normalize \
  --encode_is_query \
  --per_device_eval_batch_size 128 \
  --query_max_len 32 \
  --passage_max_len 180 \
  --dataset_name json \
  --dataset_path /data/hf-cache/datasets/downloads/bcac13e85e0ad7aadc03ba2a10a4ff6b5e9fc3866348ed139a17ecb3b13c1cf8 \
  --dataset_split train \
  --encode_output_path $2/query-dev.pkl \
  --attn_implementation sdpa
